unbind C-b
set -g prefix C-'\'
bind C-'\' send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mshkrebtan/base16-tmux'

run '~/.tmux/plugins/tpm/tpm'
